name: IGEV_Stereo
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - blas=1.0
  - brotli-python=1.0.9
  - ca-certificates
  - certifi
  - charset-normalizer=3.3.2
  - cuda-cccl=12.4.127
  - cuda-cudart=12.4.127
  - cuda-cudart-dev=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-libraries-dev=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvrtc-dev=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.127
  - cuda-opencl-dev=12.4.127
  - cuda-profiler-api=12.4.127
  - cuda-runtime=12.4.1
  - cudatoolkit=11.3.1
  - filelock=3.13.1
  - freetype=2.12.1
  - giflib=5.2.2
  - gmpy2=2.1.2
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - lcms2=2.12
  - lerc=3.0
  - libcublas=12.4.5.8
  - libcublas-dev=12.4.5.8
  - libcufft=11.2.1.3
  - libcufft-dev=11.2.1.3
  - libcurand=10.3.5.147
  - libcurand-dev=10.3.5.147
  - libcusolver=11.6.1.9
  - libcusolver-dev=11.6.1.9
  - libcusparse=12.3.1.170
  - libcusparse-dev=12.3.1.170
  - libdeflate=1.17
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.2.5.30
  - libnpp-dev=12.2.5.30
  - libnvfatbin=12.4.127
  - libnvfatbin-dev=12.4.127
  - libnvjitlink=12.4.127
  - libnvjitlink-dev=12.4.127
  - libnvjpeg=12.3.1.117
  - libnvjpeg-dev=12.3.1.117
  - libpng=1.6.39
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - networkx=3.1
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openjpeg=2.5.2
  - openssl
  - pillow=10.4.0
  - pip
  - prettytable=3.5.0
  - pysocks=1.7.1
  - python=3.8
  - pytorch=2.4.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - requests=2.32.3
  - setuptools
  - sqlite
  - sympy=1.13.2
  - tbb=2021.8.0
  - typing_extensions=4.11.0
  - urllib3=2.2.3
  - yaml=0.2.5
  - zlib
  - zstd
  - pip:
      - absl-py==2.1.0
      - cachetools==5.5.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - fonttools==4.55.2
      - fsspec==2024.10.0
      - fvcore==0.1.5.post20221221
      - google-auth==2.36.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.68.1
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iopath==0.1.10
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - markdown==3.7
      - matplotlib==3.7.5
      - oauthlib==3.2.2
      - opencv-python==4.10.0.84
      - opt-einsum==3.4.0
      - packaging==24.2
      - portalocker==3.0.0
      - protobuf==5.29.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-graphviz==0.15.0
      - pywavelets==1.4.1
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - scikit-image==0.21.0
      - scipy==1.10.1
      - six==1.17.0
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - tifffile==2023.7.10
      - timm==0.5.4
      - torchaudio==2.4.1
      - torchvision==0.20.0
      - torchviz==0.0.3
      - tqdm==4.67.1
      - werkzeug==3.0.6
      - yacs==0.1.8
      - zipp==3.20.2
